#!/bin/bash
read -p "please enter file name: " fnam
echo '++++++++++++betty+++++++++++\n'
betty $fnam
echo "++++++++++++GCC++++++++++++++\\n"
gcc $fnam 
echo "+++++++++file_output+++++++++\\n"
./a.out
gi
