#!/bin/bash
read -p "please enter file name: " fnam
printf '++++++++++++betty+++++++++++\n'
betty $fnam
printf "++++++++++++GCC++++++++++++++\n"
gcc main.c $fnam 
printf "+++++++++file_output+++++++++\n"
./a.out
~/.gita
